"""empty message

Revision ID: e2122c74b209
Revises: 
Create Date: 2026-04-04 20:00:32.883015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2122c74b209'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('slug', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('title'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('login')
    )
    op.create_table('posts',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('category_title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_login'], ['users.login'], ),
    sa.ForeignKeyConstraint(['category_title'], ['categories.title'], ),
    sa.ForeignKeyConstraint(['location_name'], ['locations.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###